<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Producte;

class ProducteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productes = [
            // 1 - Sense categoria

            // 2 - Fruites i verdures (40)
            ['nom' => 'Poma', 'categoria_id' => 2],
            ['nom' => 'Plàtan', 'categoria_id' => 2],
            ['nom' => 'Taronja', 'categoria_id' => 2],
            ['nom' => 'Mandarina', 'categoria_id' => 2],
            ['nom' => 'Maduixes', 'categoria_id' => 2],
            ['nom' => 'Síndria', 'categoria_id' => 2],
            ['nom' => 'Meló', 'categoria_id' => 2],
            ['nom' => 'Raïm', 'categoria_id' => 2],
            ['nom' => 'Llimona', 'categoria_id' => 2],
            ['nom' => 'Kiwi', 'categoria_id' => 2],
            ['nom' => 'Pera', 'categoria_id' => 2],
            ['nom' => 'Mango', 'categoria_id' => 2],
            ['nom' => 'Pinya', 'categoria_id' => 2],
            ['nom' => 'Alvocat', 'categoria_id' => 2],
            ['nom' => 'Tomàquet', 'categoria_id' => 2],
            ['nom' => 'Pebrot vermell', 'categoria_id' => 2],
            ['nom' => 'Pebrot verd', 'categoria_id' => 2],
            ['nom' => 'Ceba', 'categoria_id' => 2],
            ['nom' => 'All', 'categoria_id' => 2],
            ['nom' => 'Pastanaga', 'categoria_id' => 2],
            ['nom' => 'Enciam', 'categoria_id' => 2],
            ['nom' => 'Col', 'categoria_id' => 2],
            ['nom' => 'Bròquil', 'categoria_id' => 2],
            ['nom' => 'Coliflor', 'categoria_id' => 2],
            ['nom' => 'Espinacs', 'categoria_id' => 2],
            ['nom' => 'Moniato', 'categoria_id' => 2],
            ['nom' => 'Patata', 'categoria_id' => 2],
            ['nom' => 'Cogombre', 'categoria_id' => 2],
            ['nom' => 'Carbassó', 'categoria_id' => 2],
            ['nom' => 'Albergínia', 'categoria_id' => 2],
            ['nom' => 'Api', 'categoria_id' => 2],
            ['nom' => 'Porro', 'categoria_id' => 2],
            ['nom' => 'Xampinyons', 'categoria_id' => 2],
            ['nom' => 'Bolets variats', 'categoria_id' => 2],
            ['nom' => 'Julivert', 'categoria_id' => 2],
            ['nom' => 'Menta', 'categoria_id' => 2],
            ['nom' => 'Gingebre', 'categoria_id' => 2],
            ['nom' => 'Carxofa', 'categoria_id' => 2],
            ['nom' => 'Espàrrecs', 'categoria_id' => 2],
            ['nom' => 'Remolatxa', 'categoria_id' => 2],

            // 3 - Carn, peix i ous (40)
            ['nom' => 'Pollastre', 'categoria_id' => 3],
            ['nom' => 'Vedella', 'categoria_id' => 3],
            ['nom' => 'Porc', 'categoria_id' => 3],
            ['nom' => 'Xai', 'categoria_id' => 3],
            ['nom' => 'Bacallà', 'categoria_id' => 3],
            ['nom' => 'Tonyina', 'categoria_id' => 3],
            ['nom' => 'Salmó', 'categoria_id' => 3],
            ['nom' => 'Llom de porc', 'categoria_id' => 3],
            ['nom' => 'Costella de xai', 'categoria_id' => 3],
            ['nom' => 'Botifarra', 'categoria_id' => 3],
            ['nom' => 'Hamburguesa', 'categoria_id' => 3],
            ['nom' => 'Salsitxes', 'categoria_id' => 3],
            ['nom' => 'Pernil dolç', 'categoria_id' => 3],
            ['nom' => 'Bacó', 'categoria_id' => 3],
            ['nom' => 'Mandonguilles', 'categoria_id' => 3],
            ['nom' => 'Cuetes de pollastre', 'categoria_id' => 3],
            ['nom' => 'Ous', 'categoria_id' => 3],
            ['nom' => 'Calamar', 'categoria_id' => 3],
            ['nom' => 'Gambes', 'categoria_id' => 3],
            ['nom' => 'Musclos', 'categoria_id' => 3],
            ['nom' => 'Lluç', 'categoria_id' => 3],
            ['nom' => 'Filet de pollastre', 'categoria_id' => 3],
            ['nom' => 'Pernil salat', 'categoria_id' => 3],
            ['nom' => 'Foie', 'categoria_id' => 3],
            ['nom' => 'Gall dindi', 'categoria_id' => 3],
            ['nom' => 'Anxoves', 'categoria_id' => 3],
            ['nom' => 'Tonyina fresca', 'categoria_id' => 3],
            ['nom' => 'Costelles de porc', 'categoria_id' => 3],
            ['nom' => 'Carpaccio', 'categoria_id' => 3],
            ['nom' => 'Peix espasa', 'categoria_id' => 3],
            ['nom' => 'Croquetes', 'categoria_id' => 3],
            ['nom' => 'Pernil ibèric', 'categoria_id' => 3],
            ['nom' => 'Embotits variats', 'categoria_id' => 3],
            ['nom' => 'Sípia', 'categoria_id' => 3],
            ['nom' => 'Tonyina en oli', 'categoria_id' => 3],
            ['nom' => 'Botifarra negra', 'categoria_id' => 3],
            ['nom' => 'Costella de vedella', 'categoria_id' => 3],
            ['nom' => 'Rap', 'categoria_id' => 3],
            ['nom' => 'Cloïsses', 'categoria_id' => 3],
            ['nom' => 'Llom adobat', 'categoria_id' => 3],

            // 4 - Làctics i formatges
            ['nom' => 'Llet sencera', 'categoria_id' => 4],
            ['nom' => 'Llet desnatada', 'categoria_id' => 4],
            ['nom' => 'Llet semidesnatada', 'categoria_id' => 4],
            ['nom' => 'Iogurt natural', 'categoria_id' => 4],
            ['nom' => 'Iogurt de maduixa', 'categoria_id' => 4],
            ['nom' => 'Iogurt grec', 'categoria_id' => 4],
            ['nom' => 'Mantega', 'categoria_id' => 4],
            ['nom' => 'Margarina', 'categoria_id' => 4],
            ['nom' => 'Formatge tendre', 'categoria_id' => 4],
            ['nom' => 'Formatge curat', 'categoria_id' => 4],
            ['nom' => 'Formatge ratllat', 'categoria_id' => 4],
            ['nom' => 'Formatge fresc', 'categoria_id' => 4],
            ['nom' => 'Nata per cuinar', 'categoria_id' => 4],
            ['nom' => 'Nata per muntar', 'categoria_id' => 4],
            ['nom' => 'Llet condensada', 'categoria_id' => 4],
            ['nom' => 'Kefir', 'categoria_id' => 4],
            ['nom' => 'Llet d’ametlles', 'categoria_id' => 4],
            ['nom' => 'Llet de civada', 'categoria_id' => 4],
            ['nom' => 'Formatge de cabra', 'categoria_id' => 4],
            ['nom' => 'Formatge blau', 'categoria_id' => 4],

            // 5 - Pa, pasta i cereals
            ['nom' => 'Pa de motlle', 'categoria_id' => 5],
            ['nom' => 'Pa integral', 'categoria_id' => 5],
            ['nom' => 'Barra de pa', 'categoria_id' => 5],
            ['nom' => 'Croissants', 'categoria_id' => 5],
            ['nom' => 'Magdalenes', 'categoria_id' => 5],
            ['nom' => 'Arròs', 'categoria_id' => 5],
            ['nom' => 'Macarrons', 'categoria_id' => 5],
            ['nom' => 'Espaguetis', 'categoria_id' => 5],
            ['nom' => 'Cereals', 'categoria_id' => 5],
            ['nom' => 'Farina de blat', 'categoria_id' => 5],
            ['nom' => 'Galetes Maria', 'categoria_id' => 5],
            ['nom' => 'Galetes integrals', 'categoria_id' => 5],
            ['nom' => 'Torrades', 'categoria_id' => 5],
            ['nom' => 'Cuscús', 'categoria_id' => 5],
            ['nom' => 'Polenta', 'categoria_id' => 5],
            ['nom' => 'Blat de moro', 'categoria_id' => 5],
            ['nom' => 'Pizza base', 'categoria_id' => 5],
            ['nom' => 'Pa de cereals', 'categoria_id' => 5],
            ['nom' => 'Bastons de pa', 'categoria_id' => 5],
            ['nom' => 'Farina integral', 'categoria_id' => 5],

            // 6 - Conserves i llegums
            ['nom' => 'Mongetes cuites', 'categoria_id' => 6],
            ['nom' => 'Cigrons cuits', 'categoria_id' => 6],
            ['nom' => 'Llentilles', 'categoria_id' => 6],
            ['nom' => 'Blat de moro dolç', 'categoria_id' => 6],
            ['nom' => 'Pèsols en conserva', 'categoria_id' => 6],
            ['nom' => 'Tonyina en conserva', 'categoria_id' => 6],
            ['nom' => 'Sardines en oli', 'categoria_id' => 6],
            ['nom' => 'Tomàquet fregit', 'categoria_id' => 6],
            ['nom' => 'Tomàquet triturat', 'categoria_id' => 6],
            ['nom' => 'Olives verdes', 'categoria_id' => 6],
            ['nom' => 'Olives negres', 'categoria_id' => 6],
            ['nom' => 'Pebrots del piquillo', 'categoria_id' => 6],
            ['nom' => 'Albergínies en oli', 'categoria_id' => 6],
            ['nom' => 'Tàperes', 'categoria_id' => 6],
            ['nom' => 'Anxoves', 'categoria_id' => 6],
            ['nom' => 'Ceba fregida', 'categoria_id' => 6],
            ['nom' => 'Xampinyons en conserva', 'categoria_id' => 6],
            ['nom' => 'Salsa pesto', 'categoria_id' => 6],
            ['nom' => 'Salsa bolonyesa', 'categoria_id' => 6],
            ['nom' => 'Salsa de tomàquet picant', 'categoria_id' => 6],

            // 7 - Begudes
            ['nom' => 'Aigua mineral', 'categoria_id' => 7],
            ['nom' => 'Aigua amb gas', 'categoria_id' => 7],
            ['nom' => 'Refresc de cola', 'categoria_id' => 7],
            ['nom' => 'Refresc de taronja', 'categoria_id' => 7],
            ['nom' => 'Refresc de llimona', 'categoria_id' => 7],
            ['nom' => 'Suc de taronja', 'categoria_id' => 7],
            ['nom' => 'Suc de poma', 'categoria_id' => 7],
            ['nom' => 'Cervesa', 'categoria_id' => 7],
            ['nom' => 'Vi negre', 'categoria_id' => 7],
            ['nom' => 'Vi blanc', 'categoria_id' => 7],
            ['nom' => 'Cava', 'categoria_id' => 7],
            ['nom' => 'Sidra', 'categoria_id' => 7],
            ['nom' => 'Batut de xocolata', 'categoria_id' => 7],
            ['nom' => 'Batut de vainilla', 'categoria_id' => 7],
            ['nom' => 'Cafè', 'categoria_id' => 7],
            ['nom' => 'Tè verd', 'categoria_id' => 7],
            ['nom' => 'Tè negre', 'categoria_id' => 7],
            ['nom' => 'Cacau soluble', 'categoria_id' => 7],
            ['nom' => 'Aigua de coco', 'categoria_id' => 7],
            ['nom' => 'Beguda isotònica', 'categoria_id' => 7],

            // 8 - Snacks i dolços
            ['nom' => 'Patates fregides', 'categoria_id' => 8],
            ['nom' => 'Fruits secs barrejats', 'categoria_id' => 8],
            ['nom' => 'Pipes salades', 'categoria_id' => 8],
            ['nom' => 'Galetes de xocolata', 'categoria_id' => 8],
            ['nom' => 'Barretes de cereals', 'categoria_id' => 8],
            ['nom' => 'Xocolata negra', 'categoria_id' => 8],
            ['nom' => 'Xocolata amb llet', 'categoria_id' => 8],
            ['nom' => 'Bombons', 'categoria_id' => 8],
            ['nom' => 'Gominoles', 'categoria_id' => 8],
            ['nom' => 'Xiclets', 'categoria_id' => 8],
            ['nom' => 'Croissants de xocolata', 'categoria_id' => 8],
            ['nom' => 'Donuts', 'categoria_id' => 8],
            ['nom' => 'Pastís de poma', 'categoria_id' => 8],
            ['nom' => 'Cereals amb mel', 'categoria_id' => 8],
            ['nom' => 'Cookies', 'categoria_id' => 8],
            ['nom' => 'Palmeres', 'categoria_id' => 8],
            ['nom' => 'Pa de pessic', 'categoria_id' => 8],
            ['nom' => 'Barretes de xocolata', 'categoria_id' => 8],
            ['nom' => 'Torró', 'categoria_id' => 8],

            // 9 - Neteja de la llar
            ['nom' => 'Detergent roba', 'categoria_id' => 9],
            ['nom' => 'Suavitzant', 'categoria_id' => 9],
            ['nom' => 'Llevataques', 'categoria_id' => 9],
            ['nom' => 'Sabó de mans', 'categoria_id' => 9],
            ['nom' => 'Desinfectant', 'categoria_id' => 9],
            ['nom' => 'Amoníac', 'categoria_id' => 9],
            ['nom' => 'Fregall', 'categoria_id' => 9],
            ['nom' => 'Bayeta', 'categoria_id' => 9],
            ['nom' => 'Guants de neteja', 'categoria_id' => 9],
            ['nom' => 'Esprai per pols', 'categoria_id' => 9],
            ['nom' => 'Ambientador', 'categoria_id' => 9],
            ['nom' => 'Paper WC', 'categoria_id' => 9],
            ['nom' => 'Bosses d’escombraries', 'categoria_id' => 9],
            ['nom' => 'Raspall WC', 'categoria_id' => 9],
            ['nom' => 'Vinagre de neteja', 'categoria_id' => 9],
            ['nom' => 'Desengreixant', 'categoria_id' => 9],

            // 10 - Higiene personal
            ['nom' => 'Xampú', 'categoria_id' => 10],
            ['nom' => 'Gel de bany', 'categoria_id' => 10],
            ['nom' => 'Desodorant', 'categoria_id' => 10],
            ['nom' => 'Pasta de dents', 'categoria_id' => 10],
            ['nom' => 'Raspall de dents', 'categoria_id' => 10],
            ['nom' => 'Fil dental', 'categoria_id' => 10],
            ['nom' => 'Aigua micel·lar', 'categoria_id' => 10],
            ['nom' => 'Crema hidratant', 'categoria_id' => 10],
            ['nom' => 'Afeitadora', 'categoria_id' => 10],
            ['nom' => 'Escuma d’afaitar', 'categoria_id' => 10],
            ['nom' => 'Crema solar', 'categoria_id' => 10],
            ['nom' => 'Crema de mans', 'categoria_id' => 10],
            ['nom' => 'Bàlsam labial', 'categoria_id' => 10],
            ['nom' => 'Colònia', 'categoria_id' => 10],
            ['nom' => 'Maquineta d’afaitar', 'categoria_id' => 10],
            ['nom' => 'Sabó íntim', 'categoria_id' => 10],
            ['nom' => 'Compreses', 'categoria_id' => 10],
            ['nom' => 'Tampons', 'categoria_id' => 10],
            ['nom' => 'Cotonets', 'categoria_id' => 10],
            ['nom' => 'Cotó desmaquillant', 'categoria_id' => 10],

            // 11 - Mascotes
            ['nom' => 'Pinso per gos', 'categoria_id' => 11],
            ['nom' => 'Pinso per gat', 'categoria_id' => 11],
            ['nom' => 'Sorral per gats', 'categoria_id' => 11],
            ['nom' => 'Llauna de menjar per gos', 'categoria_id' => 11],
            ['nom' => 'Llauna de menjar per gat', 'categoria_id' => 11],
            ['nom' => 'Snacks per gos', 'categoria_id' => 11],
            ['nom' => 'Snacks per gat', 'categoria_id' => 11],
            ['nom' => 'Joguina per gos', 'categoria_id' => 11],
            ['nom' => 'Joguina per gat', 'categoria_id' => 11],
            ['nom' => 'Collar per gos', 'categoria_id' => 11],
            ['nom' => 'Corretja', 'categoria_id' => 11],
            ['nom' => 'Raspall per animals', 'categoria_id' => 11],
            ['nom' => 'Xampú per mascotes', 'categoria_id' => 11],
            ['nom' => 'Menjadora', 'categoria_id' => 11],
            ['nom' => 'Abeurador', 'categoria_id' => 11],
            ['nom' => 'Gàbia petita', 'categoria_id' => 11],
            ['nom' => 'Menjar per peixos', 'categoria_id' => 11],
            ['nom' => 'Sorral absorbent', 'categoria_id' => 11],
            ['nom' => 'Bolsa per excrements', 'categoria_id' => 11],
            ['nom' => 'Coixí per gos', 'categoria_id' => 11],

            // 12 - Bebès i infants
            ['nom' => 'Bolquers', 'categoria_id' => 12],
            ['nom' => 'Tovalloletes per nadó', 'categoria_id' => 12],
            ['nom' => 'Biberó', 'categoria_id' => 12],
            ['nom' => 'Xumet', 'categoria_id' => 12],
            ['nom' => 'Llet infantil', 'categoria_id' => 12],
            ['nom' => 'Potitos', 'categoria_id' => 12],
            ['nom' => 'Farinetes', 'categoria_id' => 12],
            ['nom' => 'Sabó suau', 'categoria_id' => 12],
            ['nom' => 'Xampú suau', 'categoria_id' => 12],
            ['nom' => 'Crema protectora', 'categoria_id' => 12],
            ['nom' => 'Joguina de bany', 'categoria_id' => 12],
            ['nom' => 'Raspall suau', 'categoria_id' => 12],
            ['nom' => 'Muda per nadó', 'categoria_id' => 12],
            ['nom' => 'Tovallola petita', 'categoria_id' => 12],
            ['nom' => 'Termòmetre', 'categoria_id' => 12],
            ['nom' => 'Chupeter', 'categoria_id' => 12],
            ['nom' => 'Biberó anticolic', 'categoria_id' => 12],
            ['nom' => 'Mossegador', 'categoria_id' => 12],
            ['nom' => 'Cullereta nadó', 'categoria_id' => 12],
            ['nom' => 'Platet infantil', 'categoria_id' => 12],

            // 13 - Farmàcia i benestar
            ['nom' => 'Paracetamol', 'categoria_id' => 13],
            ['nom' => 'Ibuprofèn', 'categoria_id' => 13],
            ['nom' => 'Tirites', 'categoria_id' => 13],
            ['nom' => 'Alcohol 70%', 'categoria_id' => 13],
            ['nom' => 'Aigua oxigenada', 'categoria_id' => 13],
            ['nom' => 'Gases estèrils', 'categoria_id' => 13],
            ['nom' => 'Termòmetre digital', 'categoria_id' => 13],
            ['nom' => 'Crema hidratant corporal', 'categoria_id' => 13],
            ['nom' => 'Crema antiinflamatòria', 'categoria_id' => 13],
            ['nom' => 'Complex vitamínic', 'categoria_id' => 13],
            ['nom' => 'Pomada calmant', 'categoria_id' => 13],
            ['nom' => 'Esprai nasal', 'categoria_id' => 13],
            ['nom' => 'Col·liri', 'categoria_id' => 13],
            ['nom' => 'Tovalloletes desinfectants', 'categoria_id' => 13],
            ['nom' => 'Mascareta quirúrgica', 'categoria_id' => 13],
            ['nom' => 'Guants d’un sol ús', 'categoria_id' => 13],
            ['nom' => 'Hidratant de llavis', 'categoria_id' => 13],
            ['nom' => 'Sèrum fisiològic', 'categoria_id' => 13],
            ['nom' => 'Líquid rentador de ferides', 'categoria_id' => 13],
            ['nom' => 'Esprai repel·lent insectes', 'categoria_id' => 13],
        ];

        Producte::insert($productes);
    }
}
